"use client";

import { ArrowUpRight, ChevronDown, Inbox, Menu, MoreHorizontal, X } from "lucide-react";
import type { Application, Status } from "./page";

const statusStyles: Record<Status, string> = { Nouveau: "status-new", Sélectionné: "status-shortlisted", "À étudier": "status-review", New: "status-new", Shortlisted: "status-shortlisted", Review: "status-review" };
const Avatar = ({ application }: { application: Application }) => <div className="avatar" style={{ background: application.color }}>{application.initials}</div>;
const Logo = () => <div className="brand-lockup"><span className="brand-mark"><span /></span><span>VIBE<span className="brand-accent">ROOM</span></span></div>;

type Props = { applications: Application[]; selected: Application; visibleApplications: Application[]; selectedId: number; setSelectedId: (id: number) => void; filter: "Toutes" | Status; setFilter: (filter: "Toutes" | Status) => void; updateStatus: (status: Status) => void; setView: (view: "landing" | "dashboard") => void; menuOpen: boolean; setMenuOpen: (open: boolean) => void; onLogout?: () => void };

export default function DashboardFr({ applications, selected, visibleApplications, selectedId, setSelectedId, filter, setFilter, updateStatus, setView, menuOpen, setMenuOpen, onLogout }: Props) {
  const filters: Array<"Toutes" | Status> = ["Toutes", "Nouveau", "Sélectionné", "À étudier"];
  return <main className="dashboard-shell">
    <aside className={`sidebar ${menuOpen ? "sidebar-open" : ""}`}><div className="sidebar-header"><Logo /><button className="icon-button mobile-menu" aria-label="Fermer le menu" onClick={() => setMenuOpen(false)}><X size={18} /></button></div><div className="workspace-switcher"><div className="workspace-avatar">V</div><div><strong>VibeRoom</strong><span>Projets VibeCode</span></div><ChevronDown size={16} /></div><nav className="side-nav"><button className="active"><Inbox size={17} /> Projets reçus <span>{applications.length}</span></button></nav><div className="sidebar-bottom"><button className="public-link" onClick={() => setView("landing")}>Voir le site public <ArrowUpRight size={15} /></button>{onLogout && <button className="logout-link" onClick={onLogout}>Se déconnecter</button>}</div></aside>
    <div className="dashboard-content"><header className="dashboard-header"><button className="icon-button dashboard-menu" aria-label="Ouvrir le menu" onClick={() => setMenuOpen(true)}><Menu size={20} /></button><div className="dashboard-title"><span className="breadcrumb">Espace privé / Projets reçus</span><h1>Projets <span>{applications.length}</span></h1></div><button className="button button-dark" onClick={() => setView("landing")}>Voir le site public <ArrowUpRight size={15} /></button></header>
      <div className="dashboard-main"><div className="review-layout review-layout-clean"><section className="application-list"><div className="list-toolbar"><div className="filter-tabs">{filters.map((item) => <button key={item} className={filter === item ? "selected" : ""} onClick={() => setFilter(item)}>{item}{item !== "Toutes" && <span>{applications.filter((application) => application.status === item).length}</span>}</button>)}</div></div><div className="list-head"><span>{visibleApplications.length} projets</span><span>Plus récents <ChevronDown size={14} /></span></div><div className="application-items">{visibleApplications.map((application) => <button key={application.id} className={`application-item ${application.id === selectedId ? "item-selected" : ""}`} onClick={() => setSelectedId(application.id)}><Avatar application={application} /><div className="applicant-summary"><strong>{application.name}</strong><span>{application.handle} · {application.location}</span></div><span className={`status-pill ${statusStyles[application.status]}`}>{application.status}</span><span className="item-time">{application.time}</span></button>)}</div></section>
        <section className="detail-panel"><div className="detail-top"><span className="detail-label">Détail du projet</span><button className="icon-button" aria-label="Plus d’options"><MoreHorizontal size={19} /></button></div><div className="detail-person"><Avatar application={selected} /><div><h2>{selected.name}</h2><span>{selected.handle} · {selected.location}</span></div></div><div className="detail-tags"><span>{selected.focus}</span><span className={`status-pill ${statusStyles[selected.status]}`}>{selected.status}</span></div><div className="detail-divider" /><div className="detail-section"><span className="detail-label">Description</span><p>{selected.bio}</p></div><div className="detail-footer"><span>Reçu {selected.time}</span><div className="status-actions"><span>Statut</span><button onClick={() => updateStatus("À étudier")} className={selected.status === "À étudier" ? "current" : ""}>À étudier</button><button onClick={() => updateStatus("Sélectionné")} className={selected.status === "Sélectionné" ? "current" : ""}>Sélectionner</button></div></div></section>
      </div></div>
    </div>
  </main>;
}
