"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowUpRight, Code2, Menu, Play, Sparkles, Trophy, X } from "lucide-react";
import SubmissionForm from "./submission-form";

/** Public landing page, with no private data requests or admin code paths. */
export default function VibePage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <main id="main" className="site-shell">
    <header className="topbar"><div className="brand-lockup"><span className="brand-mark"><span /></span><span>VIBE<span className="brand-accent">ROOM</span></span></div><nav className="desktop-nav"><a href="#concept">Le challenge</a><a href="#how">Le format</a><a href="#submit">Participer</a></nav><div className="topbar-actions"><Link className="text-button desktop-only" href="/dashboard">Espace admin <ArrowUpRight size={15} /></Link><button className="button button-dark desktop-only" onClick={() => document.getElementById("submit")?.scrollIntoView({ behavior: "smooth" })}>Soumettre un projet <ArrowUpRight size={16} /></button><button className="icon-button mobile-menu" aria-label={menuOpen ? "Fermer le menu" : "Ouvrir le menu"} aria-expanded={menuOpen} aria-controls="mobile-navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div></header>{menuOpen && <nav id="mobile-navigation" className="mobile-nav" aria-label="Navigation mobile"><a href="#concept" onClick={() => setMenuOpen(false)}>Le challenge</a><a href="#how" onClick={() => setMenuOpen(false)}>Le format</a><a href="#submit" onClick={() => setMenuOpen(false)}>Soumettre un projet</a><Link href="/dashboard">Espace admin</Link></nav>}
    <section className="hero section-pad"><div className="hero-copy"><div className="eyebrow"><span className="live-dot" />Challenge ouvert · Saison 01</div><h1>Montre ce que<br /><em>tu as construit.</em></h1><p className="hero-description">Une émission TikTok LIVE dédiée aux développeurs et vibe coders. Tu envoies ton projet, puis je le teste et je donne mon avis avec la communauté.</p><div className="hero-actions"><button className="button button-coral" onClick={() => document.getElementById("submit")?.scrollIntoView({ behavior: "smooth" })}>Envoyer mon projet <ArrowUpRight size={17} /></button><button className="watch-link" onClick={() => document.getElementById("concept")?.scrollIntoView({ behavior: "smooth" })}><span className="play-circle"><Play size={12} fill="currentColor" /></span> Comprendre le format</button></div></div><div className="hero-art"><div className="art-orbit orbit-one" /><div className="art-orbit orbit-two" /><div className="art-glow" /><div className="portrait-card"><div className="portrait-top"><span className="recording"><i /> PROJET EN DIRECT</span><span>01 / 04</span></div><div className="project-art"><Code2 size={74} /><span>BUILD<br />IN PUBLIC</span></div><div className="portrait-caption"><span>VIBE ROOM / 01</span><strong>Le projet est<br />la preuve.</strong></div></div><div className="floating-note note-one"><Sparkles size={14} /><span><b>Pas de pitch vide.</b><br />Montre le produit.</span></div><div className="floating-note note-two"><Trophy size={15} /><span>On analyse le build,<br />pas le CV.</span></div><div className="art-label">L/01 <span>Les builds en mouvement</span></div></div></section>
    <div className="ticker"><div>POUR LES DÉVELOPPEURS ✦ LES VIBE CODERS ✦ LES MAKERS ✦ LES PROJETS QUI MÉRITENT D’ÊTRE VUS ✦ POUR LES DÉVELOPPEURS ✦</div></div>
    <section id="concept" className="manifesto section-pad"><div className="section-kicker">01 — LE CHALLENGE</div><div className="manifesto-grid"><h2>Moins de<br /><em>promesses.</em><br />Plus de produit.</h2><div className="manifesto-copy"><p>VibeRoom est le rendez-vous TikTok LIVE où les développeurs soumettent leurs projets vibe-coded : applications, agents IA, outils, jeux et expériences web.</p><p>Tu envoies ton projet en ligne. Ensuite, je l’examine et je donne mon avis avec la communauté, sans que tu aies besoin d’être présent.</p><a href="#submit" className="arrow-link">Soumettre mon projet <ArrowUpRight size={16} /></a></div></div></section>
    <section id="how" className="how-section section-pad"><div className="section-kicker">02 — LE FORMAT</div><div className="section-heading"><h2>Du build<br />à l’<em>avis.</em></h2><p>Une fiche claire. Un projet réel.<br />Un retour utile et transparent.</p></div><div className="steps"><div className="step-card step-featured"><span className="step-number">01</span><div className="step-icon"><Code2 size={24} /></div><h3>Envoie ton<br />projet</h3><p>Lien, description et contexte. Pas besoin d’un dossier de 40 pages.</p><ArrowUpRight className="step-arrow" size={20} /></div><div className="step-card"><span className="step-number">02</span><div className="step-icon"><Play size={24} /></div><h3>Le projet est<br />testé</h3><p>Je découvre le produit et vérifie ce qui fonctionne réellement.</p></div><div className="step-card"><span className="step-number">03</span><div className="step-icon"><Trophy size={24} /></div><h3>Je donne<br />mon avis</h3><p>Idée, utilité, design et qualité d’exécution : les critères sont visibles.</p></div></div></section>
    <section id="submit" className="apply-section section-pad"><div className="apply-intro"><div className="section-kicker">03 — À TOI DE JOUER</div><h2>Montre le<br /><em>build.</em></h2><p>Soumets un projet que tu as vraiment construit. Le but n’est pas d’être parfait : c’est de rendre ton travail visible.</p><div className="apply-note"><Sparkles size={16} /><span>Les projets vibe-coded sont les bienvenus.<br /><strong>Les vrais liens aussi.</strong></span></div></div><SubmissionForm /></section>
    <section className="creator-section section-pad"><div className="creator-copy"><div className="section-kicker">CRÉÉ ET ANIMÉ PAR</div><h2>Salomon<br /><em>AI & Code.</em></h2><p>Je suis Salomon, ingénieur IA en Corée du Sud. Je teste des produits, je construis avec l’IA et je partage mes retours en direct.</p><a className="button button-coral" href="https://www.tiktok.com/@salomondiei" target="_blank" rel="noreferrer">Voir mon TikTok <ArrowUpRight size={16} /></a><div className="creator-links"><a href="https://www.tiktok.com/@salomondiei/video/7687011822784007442" target="_blank" rel="noreferrer"><strong>Annonce live</strong><span>Je teste vos projets en live ↗</span></a><a href="https://www.tiktok.com/@salomondiei/video/7686951883704995079" target="_blank" rel="noreferrer"><strong>Retour en live</strong><span>Les rendez-vous de la communauté ↗</span></a><a href="https://www.tiktok.com/@salomondiei/video/7680259767129869575" target="_blank" rel="noreferrer"><strong>Vibe coding</strong><span>Conseils pour bien vibe coder ↗</span></a></div></div><div className="creator-profile-card"><iframe title="Salomon présente le live de projets" src="https://www.tiktok.com/player/v1/7687011822784007442?autoplay=0" loading="lazy" allow="fullscreen" referrerPolicy="strict-origin-when-cross-origin" /><div className="creator-profile-fallback"><div className="creator-avatar">S</div><div><strong>Salomon | AI and Code</strong><span>@salomondiei · IA & code</span></div><a href="https://www.tiktok.com/@salomondiei" target="_blank" rel="noreferrer" aria-label="Ouvrir le TikTok de Salomon">↗</a></div></div></section>
    <footer className="footer section-pad"><div className="brand-lockup"><span className="brand-mark"><span /></span><span>VIBE<span className="brand-accent">ROOM</span></span></div><a href="https://www.tiktok.com/@salomondiei" target="_blank" rel="noreferrer">Les projets vibe-coded, sur mon TikTok ↗</a><Link href="/dashboard">Espace admin</Link><span>© 2026 VibeRoom · Salomon</span></footer>
  </main>;
}
